### ISSUE TITLE
Amazing addon but I can't get it to work. I get Error in line 53 in PIL/Image.py

### ISSUE THREAD

**Issue by luminati** [Wotte/2D_to_3D_blender#1]
I followed your instructions but couldn't get it to work. Tried Blender 2.69, 2.70, 2.70a, 2.71 testbuild and python 2.6 2.7 3.3 3.4 both win32 and x64 and Pillow, PIL versions accordingly. Possibly due to having windows 7 x64. I got the exact same error as window below every time.Could you help me out?
Thanks
![image](https://cloud.githubusercontent.com/assets/2597600/3226733/3d548834-f072-11e3-9b9e-45cd1137c985.png)
Lucas

**Comment by Wotte** [comment]
Hi Lucas.
Do you take the "PIL" folder on GitHub ? if yes, try to download here http://www.lfd.uci.edu/~gohlke/pythonlibs/ 

If not, Wait a little bit, i'm programming a software. with this software, you don't need "Pillow" ^.^

**Comment by luminati** [comment]
Tried this one from github and one precompiled for x64 python. Neither work. Which version of Blender have you tested it on and was it 32 bit or 64?

**Comment by Wotte** [comment]
Blender 2.70 with windows 32 bits, take on the website http://www.lfd.uci.edu/~gohlke/pythonlibs/ not on GitHub.
